### ISSUE TITLE
composer require problem

### ISSUE THREAD

**Issue by ddfire** [adelplace/onesignal-bundle#1]
Hello
i am getting this
 composer require adelplace/onesignalbundle
                                                                                                                                                             
  [InvalidArgumentException]                                                                                                                                 
  Could not find package adelplace/onesignalbundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Any ideas?
Thanks!!!!

My composer.json file is
{
	"name" : "dfaerman/dailyheroes",
	"license" : "proprietary",
	"type" : "project",
	"prefer-stable": true,
	"minimum-stability": "dev",
	"autoload" : {
		"psr-4" : {
			"" : "src/"
		},
		"classmap" : [
			"app/AppKernel.php",
			"app/AppCache.php"
		]
	},
	"autoload-dev" : {
		"psr-4" : {
			"Tests\\" : "tests/"
		},
		"files" : [
			"vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php"
		]
	},
	"require" : {
		"php" : ">=5.5.9",
		"adelplace/onesignalbundle" : "1.0",
		"doctrine/doctrine-bundle" : "^1.6",
		"doctrine/orm" : "^2.5",
		"friendsofsymfony/rest-bundle" : "^2.2",
		"friendsofsymfony/user-bundle" : "^2.0",
		"incenteev/composer-parameter-handler" : "^2.0",
		"jms/serializer-bundle" : "^2.2",
		"lexik/jwt-authentication-bundle" : "^2.4",
		"nelmio/api-doc-bundle" : "^2.13",
		"nelmio/cors-bundle" : "^1.5",
		"sensio/distribution-bundle" : "^5.0.19",
		"sensio/framework-extra-bundle" : "^3.0.2",
		"symfony/monolog-bundle" : "^3.1.0",
		"symfony/polyfill-apcu" : "^1.0",
		"symfony/swiftmailer-bundle" : "^2.3.10",
		"symfony/symfony" : "3.3.*",
		"twig/twig" : "^1.0||^2.0"
	},
	"require-dev" : {
		"behat/behat" : "^3.4",
		"behat/symfony2-extension" : "^2.1",
		"csa/guzzle-bundle" : "^2.2",
		"guzzlehttp/guzzle" : "^6.3",
		"phpunit/phpunit" : "^6.4",
		"sensio/generator-bundle" : "^3.0",
		"symfony/phpunit-bridge" : "^3.0"
	},
	"scripts" : {
		"post-install-cmd" : [
			"@symfony-scripts"
		],
		"post-update-cmd" : [
			"@symfony-scripts"
		]
	},
	"config" : {
		"sort-packages" : true
	},
	"extra" : {
		"symfony-app-dir" : "app",
		"symfony-bin-dir" : "bin",
		"symfony-var-dir" : "var",
		"symfony-web-dir" : "web",
		"symfony-tests-dir" : "tests",
		"symfony-assets-install" : "relative",
		"incenteev-parameters" : {
			"file" : "app/config/parameters.yml"
		}
	}
}

**Comment by ddfire** [comment]
yeah i know the name is wrong
https://packagist.org/packages/adelplace/onesignal-bundle
has the typo in the second section of the page its says:
Getting Started

Installing
Just require the bundle with composer

composer require adelplace/**onesignalbundle**

**Comment by ddfire** [comment]
The typo is in the readme.md file....
Ok i am installing let you know later.
Thanks

**Comment by adelplace** [comment]
Hi,

Thank you for your feedback, the readme is up to date now.
